#!/usr/bin/env perl

# test_function
# scratch space for accounting_cruft_probe

BEGIN {unshift @INC, '/usr/local/cpanel';}

use strict;
use warnings;
use File::Find;

my $domain = 'cpblainem.com';
my (@userdata_files, @results, );


print_results ();


sub check_userdata_files {
    opendir (my $dh, '/var/cpanel/userdata')
        or warn "could not open /var/cpanel/userdata\n";
        while (my $userdata_file = readdir($dh)) {
            if ($userdata_file eq '.' || $userdata_file eq '..') {  # if the listing is a . or ..
                next;  # ignore and move on
            }
            push (@userdata_files, "/var/cpanel/userdata/$userdata_file");  # build array of users files
        }
    closedir $dh;
    undef $userdata_file;
    foreach my $userdata_file (@userdata_files) {
        open (my $fh, '<', $userdata_file)
            or warn "could not open $userdata_file\n";
            foreach (<$fh>) {
                if (/$domain/) {
                    if (/XDNS/) {
                        last;
                    } else {
                        push (@results, $userdata_file);
                        last;
                    }
                }
            }
        close $fh;
    }
}


sub print_results {
    print "results:\n";
    if (scalar (@results) == 0) {
        print "nothing was found\n";
    } else {
        foreach (@results) {
            print "$_\n";
        }
    }
    print "\n";
    exit; 
}
